# Generated by Django 3.2.12 on 2022-07-24 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220724_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
        migrations.AddField(
            model_name='review',
            name='emoji',
            field=models.CharField(choices=[('😐', 'Indifferent'), ('😍', 'Loved it'), ('🙁', 'Hated it')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='examStars',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='lectureStars',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
